config/routes.rb
Rschedule::Application.routes.draw do

  resources :calendar, :only => :show
  resources :events, :except => [:index, :list] do
    member do
      post 'edit'
    end
  end

  resources :weeks, :only => [:index, :show] do
    member do
      get 'change_month'
      get 'change_week'
    end
  end
  
  root :to => "weeks#index"
  match ':controller(/:action(/:id(.:format)))'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :set_calendar

  protected
  def set_calendar
    @calendar = Calendar.first
  end
end

app/controllers/calendar_controller.rb
class CalendarController < ApplicationController
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def create
    @calendar_event = @calendar.events.create(params[:calendar_event])
    respond_to_change
  end
  
  def new
    @calendar_event = CalendarEvent.new
    respond_to do |format|
      format.html
      format.js
    end
  end
  
  def edit
    @calendar_event = CalendarEvent.find(params[:id])
    respond_to do |format|
      format.html
      format.js
    end 
  end
  
  def update
    @calendar_event = CalendarEvent.find(params[:id])
    @calendar_event.update_attributes(params[:calendar_event]) if @calendar_event
    respond_to_change
  end

  def destroy
    @calendar_event = CalendarEvent.destroy(params[:id])
    respond_to_change
  end
  
  protected
  def respond_to_change
    respond_to do |format|
      format.html { redirect_to(root_url) }
      format.js { render :update }
    end
  end    
end

app/controllers/weeks_controller.rb
class WeeksController < ApplicationController
  include ScheduleFu::ScheduleFuHelper
  
  def index
    show
    render :action => 'show'
  end
  
  def show
    params[:id] ||= session[:sf_week_sunday]
    sunday = previous_sunday(params[:id])
    session[:sf_week_sunday] = sunday.to_s
    saturday = 6.days.since sunday
    set_dates sunday..saturday
  end
  
  def change_month
    @selected_date = parse_date_or_now(params[:id]) 
  end
  
  def change_week
    show
  end
  
  protected
  
  def set_dates(range)
    @dates = CalendarDate.get_and_create_dates(range)
    max = @calendar.max_events_per_day_without_time_set(range)
    @without_time_range = 0..(max - 1)
    @selected_date = parse_date_or_now(params[:id]) 
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include ScheduleFu::CalendarHelper
  include ScheduleFu::ScheduleFuHelper

  def flash_div *keys
    divs = "".html_safe
    keys.each do |k|
      divs << content_tag(:div, flash[k], :class => "flash #{k}", :id => "flash-#{k}")
    end
    divs
  end
  
  def close_link
    content_tag(:div, :class => "sf-close") do
      link_to "X", "#"
    end
  end
end

app/helpers/calendar_helper.rb
module CalendarHelper
end

app/helpers/events_helper.rb
module EventsHelper
  def event_types
    CalendarEventType.all.collect {|t| [t.desc, t.id]}
  end
  
  def recurrence_style(*event_types)
    display = @calendar_event.event_type_matches?(*event_types)
    style = display ? "block" : "none"
    "display: #{style};"
  end
end

app/helpers/weeks_helper.rb
module WeeksHelper
  def small_calendar
    calendar(:year => @selected_date.year, :month => @selected_date.mon,
        :abbrev => 0..0, :previous_month_text => previous_month_link,
        :next_month_text => next_month_link, 
        :month_name_array => Date::ABBR_MONTHNAMES, 
        :display_year => @selected_date.strftime("%y")) do |d|
      [link_to(d.mday, change_week_week_url(d.to_date.to_s), 
          :remote => true, :class => "normalDay")]
    end
  end

  def date_display
    return unless @dates
    from = @dates.first.value
    to = @dates.size > 1 ? @dates.last.value : nil
    
    from_display = from.strftime("%b %d")
    from_display << from.strftime(", %Y") unless to && from.year == to.year
    to_display = ""
    if to
      to_display << to.strftime("%b ") unless from.month == to.month
      to_display << to.strftime("%d, %Y")
    end
    "#{from_display} - #{to_display}"
  end
  
  def event_time(start_time, end_time)
    "#{time_format(start_time)} - #{time_format(end_time)}"
  end
  
  def time_format(time)
    time.strftime("%I:%M%p").downcase
  end
  
  def event_day_desc(event)
    event_desc_to_size(event, 25) if event
  end
  
  def event_hour_desc(event)
    event_desc_to_size(event, 50) if event
  end
  
  def event_desc_to_size(event, size)
    "#{recurring_symbol(event)}#{event.desc}"[0,size]
  end
  
  def recurring_symbol(event)
    'R ' if event.recurrences.size > 0 
  end
  
  def previous_week_link
    day = 7.days.ago(@selected_date.wday.ago(@selected_date))
    link_to("<", change_week_week_url(day), :remote => true)
  end
  
  def next_week_link
    day = 7.days.since(@selected_date.wday.ago(@selected_date))
    link_to(">", change_week_week_url(day), :remote => true)
  end
  
  def today_link
    link_to("Today", change_week_week_url(Time.now.to_date.to_s), :remote => true)
  end
 
  def hidden_nav_link
    link_to("", change_week_week_url(@selected_date), :remote => true, :id => 'sf-selected-date-nav-link')
  end

  def previous_month_link
    day = 1.day.ago @selected_date.beginning_of_month
    content_tag(:span, :id => 'sf-previous-month-link') do
      link_to "<", change_month_week_url(day), :remote => true
    end
  end
  
  def next_month_link
    day = 1.day.since @selected_date.end_of_month
    content_tag(:span, :id => 'sf-next-month-link') do
      link_to ">", change_month_week_url(day), :remote => true
    end
  end
  
  def add_event_link
    link_to("Add Event", new_event_url, :remote => true, :id => "sf-add-event-link")
  end
  
  def edit_event_link(event)
    return if event.nil?
    link_to "", edit_event_url(event), :class => "sf-hidden-edit-event-link", :remote => true
  end
end

app/views/calendar/_nav.html.erb
<div id="sf-nav">
  <table cellspacing="0" cellpadding="0">
    <tbody>
      <tr>
        <td>
          <%= link_to "<", :controller => 'calendar', :action => 'week', :id => 'last' %>
        </td>
        <td>
          <%= link_to ">", :controller => 'calendar', :action => 'week', :id => 'next' %>
        </td>
        <td>
          <%= button_to 'Today' %>
        </td>
        <td>
          <%= date_display %>
        </td>
      </tr>
    </tbody>
  </table>
</div>

app/views/events/_edit_form.html.erb
<%= flash_div 'new-error' %>
<%= form_for(:calendar_event, :url => event_url(@calendar_event), 
       :method => :put, :remote => true) do |f| %>
  <%= render :partial => 'form', :locals => {:f => f} %>
<% end %> 

<%= link_to "Delete", event_url(@calendar_event), :remote => true, 
        :confirm => 'Are you sure?', :method => :delete %>

app/views/events/_form.html.erb
<%= f.hidden_field :calendar_id, :value => @calendar.id %>
<div class="flash error" id="flash-new-error"></div>
<table>
  <tr>
    <td>
      <%= f.label :desc, "Event:" %>
    </td>
    <td>
      <%= f.text_field :desc, :size => 50 %>
    </td>
  </tr>
  <tr>
    <td>
      <%= f.label :start_date, "From date:" %>
    </td>
    <td>
      <%= f.hidden_field :start_date %>
      <%= text_field_tag :show_start_date, @calendar_event.start_date,
              :class => "datepicker" %>
    </td>
  </tr>
  <tr>
    <td>
      <%= f.label :start_time, "From time:" %>
    </td>
    <td>
      <%= f.text_field :start_time, :class => "timepicker" %>
    </td>
  </tr>
  <tr>
    <td>
      <%= f.label :end_time, "To time:" %>
    </td>
    <td>
      <%= f.text_field :end_time, :class => "timepicker" %>
    </td>
  </tr>
  <tr>
    <td>
      <%= f.label :end_date, "To date:" %>
    </td>
    <td>
      <%= f.hidden_field :end_date %>
      <%= text_field_tag :show_end_date, @calendar_event.end_date,
              :class => "datepicker" %>
    </td>
  </tr>
  <tr>
    <td>
      Repeats:
    </td>
    <td>
      <%= render :partial => 'repeats', :locals => {:f => f} %>
    </td>
  <tr>
    <td>
      <%= f.label :long_desc, "Description:" %>
    </td>
    <td>
      <%= f.text_area :long_desc, :cols => 50, :rows => 15 %>
    </td>
  </tr>
  <tr>
    <td colspan="2">
      <%= submit_tag %>
    </td>
  </tr>
</table>

app/views/events/_new_form.html.erb
<%= flash_div 'new-error' %>
<%= form_for(:calendar_event, :url => events_url, :remote => true) do |f| %>
  <%= render :partial => 'form', :locals => {:f => f} %>
<% end %>

app/views/events/_repeat_by.html.erb
<div id="sf-recurrence-repeat-by" style="<%= recurrence_style('monthly', 'yearly') %>">
  <%= f.radio_button(:by_day_of_month, false)%> Day of the week
  <%= f.radio_button(:by_day_of_month, true)%> Day of the month
</div>

app/views/events/_repeats.html.erb
<%= f.select :calendar_event_type_id, event_types, {}, {:id => 'sf-event-recurrence-type'} %>

<%= render :partial => 'repeats_weekly', :locals => {:f => f} %>
<%= render :partial => 'repeats_monthly', :locals => {:f => f} %>
<%= render :partial => 'repeats_yearly', :locals => {:f => f} %>
<%= render :partial => 'repeat_by', :locals => {:f => f} %>

app/views/events/_repeats_monthly.html.erb
<div id="sf-recurrence-monthly" style="<%= recurrence_style('monthly') %>">
  <%= f.label "repeat_by", "Repeat by:" %><br/>
</div>

app/views/events/_repeats_weekly.html.erb
<div id="sf-recurrence-weekly" style="<%= recurrence_style('weekly') %>">
  <%= f.label "repeat_by", "Repeat on:" %><br/>
  <table>
    <tr>
      <%= text = "".html_safe 
          (0..6).each {|d| text << content_tag(:td, f.check_box("repeat_#{d}")) }  
          text
      %>
    </tr>
    <tr>
      <%= raw %w{S M T W T F S}.collect {|d| "<td>#{d}</td>"}.join %>
    </tr>
  </table>
</div>

app/views/events/_repeats_yearly.html.erb
<div id="sf-recurrence-yearly" style="<%= recurrence_style('yearly') %>">
  <%= f.label "repeat_by", "Repeat by:" %><br/>
</div>

app/views/events/edit.html.erb
<%= render partial: 'edit_form' %>

app/views/events/new.html.erb
<%= render partial: 'new_form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rschedule</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/weeks/_calendar.html.erb
<%= render :partial => 'nav'%>
<table id="sf-grid">
  <%= render :partial => 'week_days' %>
  <tr id="sf-week-hours">
    <%= render :partial => 'hours' %>
    <%= render :partial => 'week_hours' %>
  </tr>
</table>

app/views/weeks/_hours.html.erb
<td>
  <% time_range = (1..11).to_a.insert(0, 12) 
     time_range.each do |i| %>
    <div class="sf-hour">
      <%= i %>am
    </div>
  <% end %>
  <% time_range.each do |i| %>
    <div class="sf-hour">
      <%= i %>pm
    </div>
  <% end %>
</td>

app/views/weeks/_nav.html.erb
<div id="sf-nav">
  <table cellspacing="0" cellpadding="0">
    <tbody>
      <tr>
        <td>
          <%= previous_week_link %>
        </td>
        <td>
          <%= today_link %>
          <%= hidden_nav_link %>
        </td>
        <td>
          <%= next_week_link %>
        </td>
        <td>
          <%= date_display %>
        </td>
        <td>
          <%= add_event_link %>
          <div id="sf-add-event" style="display: none;">
            <%= close_link %>
              <div id="sf-add-event-content"></div>
          </div>
        </td>
        <td>
          <%= flash_div :notice, :warning, :error %>
        </td>
      </tr>
    </tbody>
  </table>
</div>

app/views/weeks/_small_calendar.html.erb
<%= calendar(:year => @selected_date.year, :month => @selected_date.mon,
        :abbrev => 0..0, :previous_month_text => previous_month_link,
        :next_month_text => next_month_link, 
        :month_name_array => Date::ABBR_MONTHNAMES, 
        :display_year => @selected_date.strftime("%y")) do |d|
      [link_to(d.mday, change_week_week_url(d.to_date.to_s), 
          :remote => true, :class => "normalDay")]
    end
%>

app/views/weeks/_week_days.html.erb
<tr class="sf-week-days">
  <td></td>
  <% @dates.each do |date| %>
    <td class="sf-week-day">
      <%= date.value.strftime("%a %m/%d") %>
    </td>
  <% end %>
</tr>
<% @without_time_range.each do |i| %>
  <tr class="sf-week-days">
    <td></td>
    <% @dates.each do |date| %>
      <% if event = date.events.without_time_set[i] %>
        <td class="sf-week-event">
          <%= edit_event_link(event) %>
          <div class="sf-open-edit-window">
            <%= event_day_desc(event) %>
          </div>
        </td>
      <% else %>
        <td></td>
      <% end %>
    <% end %>
  </tr>
<% end %>
<tr class="sf-week-days">
  <td></td>
  <% @dates.each do %>
    <td></td>
  <% end %>
</tr>

app/views/weeks/_week_hours.html.erb
<% @dates.each do |date| %>
  <td class="sf-week-event-column">
    <% date.events.with_time_set.order(:start_time).each do |event| %>
      <% top = event.start_time.hour * 40 %>
      <% bottom = (40 * 24) - (event.end_time.hour * 40)%>
      <div>
        <%= edit_event_link(event) %>
        <div class="sf-week-event sf-open-edit-window" style="top: <%= top %>px; bottom: <%= bottom %>px;">
          <div class="sf-week-event-hours">
            <div>
              <%= event_time(event.start_time, event.end_time) %>
            </div>
          </div>
          <div class="sf-week-event-desc">
            <%= edit_event_link(event) %>
            <div>
              <%= event_hour_desc(event) %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </td>
<% end %>

app/views/weeks/show.html.erb
<table id="sf-main" cellspacing="0" cellpadding="0">
  <tbody>
    <tr>
      <td id="sf-section1" class="sf-section">
        <div id="sf-small-calendar">
          <%= raw small_calendar %>
        </div>
      </td>
      <td id="sf-section2" class="sf-section">
        <div id="sf-main-calendar">
          <%= render :partial => 'calendar' %>
        </div>
      </td>
    </tr>
  </tbody>
</table>